

            <!-- SLIDER -->
            <div class="slider-wrap">
                <div class="tp-banner-container">
                    <div class="tp-banner" >
                        <ul>
                            <!-- SLIDE  -->
                            <li data-transition="fade" data-slotamount="2" data-masterspeed="500" data-thumb="homeslider_thumb1.jpg"  data-saveperformance="on"  data-title="Intro Slide">
                                <!-- MAIN IMAGE -->
                                <img src="images/dummy.png"  alt="slidebg1" data-lazyload="images/slides/2.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                                <!-- LAYERS -->
                                <div class="tp-caption customin fadeout tp-resizeme rs-parallaxlevel-10"
                                     data-x="center"
                                     data-y="center"
                                     data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                     data-speed="800"
                                     data-start="1000"
                                     data-easing="Power3.easeInOut"
                                     data-splitin="none"
                                     data-splitout="none"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="300"
                                     style="z-index: 2; max-width: 630px; max-height: 250px; background:#fff;width:100%;height:100%; white-space: nowrap;">
                                </div>
                                <!-- LAYER NR. 2 -->
                                <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                     data-x="center"
                                     data-y="250"
                                     data-speed="1000"
                                     data-start="1400"
                                     data-easing="Power3.easeInOut"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="1000"
                                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;font-family: Raleway;
                                     font-size: 36px;
                                     font-weight: bold;
                                     text-transform: uppercase;	color: #343434;">Amazing <span class="ss-color" style="color:#d6644a;">Outlet</span></div>
                                <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                     data-x="center"
                                     data-y="310"
                                     data-speed="1000"
                                     data-start="1800"
                                     data-easing="Power3.easeInOut"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="1000"
                                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;	font-family: Raleway;
                                     font-size: 18px;
                                     color: #333;text-align:center;">
                                    Clean & Elegant design with a modern style. This template includes<br>
                                    all you need for a fashion & accessories store
                                </div>
                                <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                     data-x="center"
                                     data-y="375"
                                     data-speed="1000"
                                     data-start="2200"
                                     data-easing="Power3.easeInOut"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="1000"
                                     style="z-index: 3; max-width: 80px; max-height: 4px; width:100%;height:100%;background:#000000;"></div>
                                <a href="./categories-grid.html" class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                   data-x="center"
                                   data-y="395"
                                   data-speed="1000"
                                   data-start="2600"
                                   data-easing="Power3.easeInOut"
                                   data-elementdelay="0.1"
                                   data-endelementdelay="0.1"
                                   data-end="7300"
                                   data-endspeed="1000"
                                   style="z-index: 3; max-height:100%;line-height:43px;color:#fff;font-family: Montserrat;
                                   font-size: 12px;
                                   display:table;
                                   font-weight: bold;
                                   text-transform:uppercase;padding:0 40px;background:#000000;position:relative;z-index:77;">
                                    Shop Now !
                                </a>
                            </li>
                            <li data-transition="fade" data-slotamount="2" data-masterspeed="500" data-thumb="homeslider_thumb1.jpg"  data-saveperformance="on"  data-title="Intro Slide">
                                <!-- MAIN IMAGE -->
                                <img src="images/dummy.png"  alt="slidebg1" data-lazyload="images/slides/1.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                                <!-- LAYERS -->
                                <div class="tp-caption customin fadeout tp-resizeme rs-parallaxlevel-10"
                                     data-x="center"
                                     data-y="center"
                                     data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                     data-speed="800"
                                     data-start="1000"
                                     data-easing="Power3.easeInOut"
                                     data-splitin="none"
                                     data-splitout="none"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="300"
                                     style="z-index: 2; max-width: 630px; max-height: 250px; background:#fff;width:100%;height:100%; white-space: nowrap;">
                                </div>
                                <!-- LAYER NR. 2 -->
                                <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                     data-x="center"
                                     data-y="250"
                                     data-speed="1000"
                                     data-start="1400"
                                     data-easing="Power3.easeInOut"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="1000"
                                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;font-family: Raleway;
                                     font-size: 36px;
                                     font-weight: bold;
                                     text-transform: uppercase;	color: #343434;">Women <span class="ss-color" style="color:#d6644a;">Clothing</span>
                                </div>
                                <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                     data-x="center"
                                     data-y="310"
                                     data-speed="1000"
                                     data-start="1800"
                                     data-easing="Power3.easeInOut"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="1000"
                                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;	font-family: Raleway;
                                     font-size: 18px;
                                     color: #333;text-align:center;">
                                    Clean & Elegant design with a modern style. This template includes<br>
                                    all you need for a fashion & accessories store
                                </div>
                                <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                     data-x="center"
                                     data-y="375"
                                     data-speed="1000"
                                     data-start="2200"
                                     data-easing="Power3.easeInOut"
                                     data-elementdelay="0.1"
                                     data-endelementdelay="0.1"
                                     data-end="7300"
                                     data-endspeed="1000"
                                     style="z-index: 3; max-width: 80px; max-height: 4px; width:100%;height:100%;background:#000000;">
                                </div>
                                <a href="./categories-grid.html" class="tp-caption lft skewtoleftshort rs-parallaxlevel-9"
                                   data-x="center"
                                   data-y="395"
                                   data-speed="1000"
                                   data-start="2600"
                                   data-easing="Power3.easeInOut"
                                   data-elementdelay="0.1"
                                   data-endelementdelay="0.1"
                                   data-end="7300"
                                   data-endspeed="1000"
                                   style="z-index: 3; max-height:100%;line-height:43px;color:#fff;font-family: Montserrat;
                                   font-size: 12px;
                                   display:table;
                                   font-weight: bold;
                                   text-transform:uppercase;padding:0 40px;background:#000000;position:relative;z-index:77;">
                                    Shop Now !
                                </a>
                            </li>
                        </ul>
                        <div class="tp-bannertimer"></div>
                    </div>
                </div>
            </div>

            <!-- BLOCKS WRAP -->
            <div class="block-main container">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="block-content">
                            <img src="images/blocks/1.jpg" class="img-responsive" alt=""/>
                            <div class="bs-text-down text-center hvr-outline-out">
                                Menswear<span>Intimates Fall/Winter 2015</span>				
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="block-content">
                            <img src="images/blocks/2.jpg" class="img-responsive" alt=""/>
                            <div class="bs-text-center text-center">
                                Accesories<span>Get a new look with Smile Collection</span>				
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="block-content">
                            <img src="images/blocks/3.jpg" class="img-responsive" alt=""/>
                            <div class="bs-text-down text-center">
                                Womenswear<span>Smile Collection new arrivals</span>				
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <!-- FEATURED PRODUCTS -->
            <div class="featured-products">
                <div class="container">
                    <div class="row">
                        <h5 class="heading"><span>Featured Products</span></h5>
                       
                        <div id="isotope" class="isotope">

                            <?php foreach($produits as $prod){?>
                            <div class="isotope-item">
                                <div class="product-item">
                                    <div class="item-thumb">
                                        <img src="<?php echo $prod['image']; ?>" class="img-responsive" alt=""/>
                                    </div>
                                    <div class="product-info">
                                        <h4 class="product-title"><a href="./single-product.html"><?php echo $prod['titre']; ?></a></h4>
                                        <span class="product-price"><?php echo $prod['prix']; ?>€ </span>
                                        
                                    </div>
                                </div>
                            </div>
                            <?php }?>
                           
                 
                            
                        </div>
                    </div>
                </div>
            </div>

           
           

        