



            

            <!-- PAGE HEADER -->
            <div class="page_header">
                <div class="container">
                    <div class="page_header_info text-center">
                 
                        <div class="page_header_info_inner">
                            <h2><?php echo $_GET['recherche']; ?></h2>
                            
                        </div>
                        
                    </div>
                </div>
            </div>

               <div class="featured-products">
                <div class="container">
                    <div class="row">
                        <h5 class="heading"><span></span></h5>
                       
                        <div id="isotope" class="isotope">

                            <?php foreach($produits as $prod){?>
                                <?php while($a = $produits->fetch()) { ?>
                            <div class="isotope-item">
                            
                                <div class="product-item">


                             
                                    <div class="item-thumb">
                                    <img src="<?php echo $a['image'];?>" style="max-width:100%;">
                                    </div>
                                    
                                    <div class="product-info">
                                        <h4 class="product-title"><a href="produit.php?id=<?php echo $prod['id'];?>"><?php echo $prod['titre']; ?></a></h4>
                                        <span class="product-price"><?php echo $prod['prix']; ?> </span>
                                        
                                    </div>
                                </div>
                                
                            </div>
                            <?php } ?> 
                            <?php }?>
                           
                          
                         
                         
                            



                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix space20"></div>